symbols_regex = /^[a-z0-9-]+$/
category_max_length = 64
action_max_length = 64
value_max_length = 768
user_agent_length = 1024
cls_max_length = 20 # Max length of an individual cls
max_classes_per_log = 12 # Max classes per log
actionClassesSimpleSchemaCustomValidator = ->
  if @isSet
    for cls in @value
      if cls.length > cls_max_length
        e = "Log class #{cls} is longer than #{cls_max_length} chars"
        console.error e

        return e
      
      if @value.length > max_classes_per_log
        e = "Log can have up to #{max_classes_per_log} classes."
        console.error e

        return e

      if not symbols_regex.test(cls)
        e = "Invalid symbol"
        console.error e

        return e

  return undefined

LogsRegistrarActionSchema = new SimpleSchema
  action_id:
    label: "Action ID"

    type: String

    regEx: symbols_regex

    max: action_max_length

  description:
    label: "Action description"

    type: String

  classes:
    # At the moment classes are just set the base
    # classes, the JA call can augment the classes
    # listed here, but we gurentee, that all events
    # written will include at the minimum the classes
    # you list here.
    label: "Action classes"

    type: [String]

    custom: actionClassesSimpleSchemaCustomValidator

    optional: true

LogsRegistrarActionsSchema = new SimpleSchema 
  actions:
    type: [LogsRegistrarActionSchema]

ConnectIdentificationObjectSchema = new SimpleSchema
  DID:
    # Device ID is set for the device by the client (the web-app / mobile app).
    #
    # It should survive between reopening of the app, connection reset,
    # login/logout.
    #
    # Expected to be a random string consisting of 17 characters (on Meteor: it
    # should be generated by Random.id()).

    label: "Device ID"

    type: String

    min: 17
    max: 17

  SID:
    # Session ID - A unique ID set for the session by the client.
    #
    # The following should be regarded as new sessions:
    #
    #   * Reopening a mobile application
    #   * Opening a new tab
    #
    # Should survive server connection interruptions.
    # Should move with the user between landing app and web app.
    #
    # Expected to be a random string consisting of 17 characters (on Meteor: it
    # should be generated by Random.id()).

    label: "Session ID"

    type: String

    min: 17
    max: 17

  appVersion:
    # The current client application version (on Mobile that should be the
    # build number).
    label: "Application version"

    type: String

    defaultValue: ""

    min: 0
    max: 64

  CType:
    # Should be the client environment unique ID (examples: web-app / landing-app  / android / ios)
    label: "Client type"

    type: String

    min: 0
    max: 64

  userAgent:
    # On the web-apps detected automatically from HTTP header, on Mobile
    # should be a string with details about the phone (Device Type, OS release, etc.)
    label: "User agent"

    type: String

    defaultValue: ""

    min: 0
    max: user_agent_length

ReceivedLogObjectSchema = new SimpleSchema
  cat:
    label: "Category"

    type: String

    regEx: symbols_regex

    max: category_max_length

  act:
    label: "Action ID"

    type: String

    regEx: symbols_regex

    max: action_max_length

  val:
    label: "Action value"

    type: String

    optional: true

    autoValue: ->
      # Trim value if longer than allowed length
      if @isSet
        if @value > value_max_length
          return @value.substr(0, value_max_length)
        
      return undefined # meaning - don't change

  cls:
    # Will extend, not replace, the classes the
    # action was registered with.
    # See LogsRegistrarActionSchema.classes simple
    # schema definition above
    label: "Action classes"

    type: [String]

    custom: actionClassesSimpleSchemaCustomValidator

    optional: true

  pid:
    label: "Project ID"

    type: String

    optional: true

    max: 17

ASIDObjectSchema = new SimpleSchema
  # The following is not a full definition, it is partial for the definition required
  # by justdo-user-active-position
  SSID:
    label: "Server Session ID"

    type: String

    min: 15
    max: 30

# Note: static binding

JustdoAnalytics.schemas_consts =
  symbols_regex: symbols_regex
  category_max_length: category_max_length
  action_max_length: action_max_length
  value_max_length: value_max_length
  cls_max_length: cls_max_length
  user_agent_length: user_agent_length
  max_classes_per_log: max_classes_per_log

JustdoAnalytics.schemas =
  LogsRegistrarActionSchema: LogsRegistrarActionSchema
  LogsRegistrarActionsSchema: LogsRegistrarActionsSchema
  ConnectIdentificationObjectSchema: ConnectIdentificationObjectSchema
  ReceivedLogObjectSchema: ReceivedLogObjectSchema
  ASIDObjectSchema: ASIDObjectSchema
