_.extend JustDoProjectsTemplates,
  template_grid_views:
    gantt:
      [
        "field":"title",
        "width":400,
        "filter":null,
        "frozen":true
      ,
        "field":"justdo_grid_gantt",
        "width":633
      ,
        "field":"jpu:basket_start_date_formatter",
        "width":122,
        "filter":null
      ,
        "field":"jpu:basket_end_date_formatter",
        "width":122,
        "filter":null
      ,
        "field":"due_date",
        "width":122,
        "filter":null
      ,
        "field":"state",
        "width":122,
        "filter":null
      ]