_.extend JustdoChat,
  jdc_info_pseudo_collection_name: "JDChatInfo"
  jdc_recent_activity_channels_collection_name: "JDChatRecentActivityChannels"
  jdc_recent_activity_messages_collection_name: "JDChatRecentActivityMessages"
  jdc_recent_activity_authors_details_collection_name: "JDChatRecentActivityAuthorsDetails"